baseURL: "https://saraasgarigouraj.github.io/"
title: Sara Asgari
paginate: 14
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Teaching
      url: /courses/
      weight: 1
    - name: Research
      url: /papers/
      weight: 2
    - name: CV
      url: /cv.pdf
      weight: 3

params:
  description: |
    Welcome!
    I am a Ph.D. candidate in Economics at the University of Oklahoma–Norman, with research interests in environmental economics, energy economics, and public economics. I will be on the job market in Fall 2025.

    My job market paper, Market Dispatch and Emissions in U.S. Electricity Markets: Spatial Reallocation and Operational Efficiency, studies how market dispatch reshapes generation patterns and emissions through operational efficiency and reallocation across regions.
  author: Sara Asgari
  googleAnalyticsID: "G-WHEYZ77X40"
  DateFormat: "January 2006"   # Go time layout, not a literal date
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false

  profileMode:
    enabled: true
    title: "<span style='font-size: 26px;'>Sara Asgari</span>"
    subtitle: |
                <div style="margin-bottom: 0.2cm;"></div>
                Welcome!
                <div style="margin-bottom: 0.5cm;"></div>
                I am a Ph.D. candidate in Economics at the University of Oklahoma–Norman, with research interests in environmental economics, energy economics, and their intersection with public policy. I will be on the job market in Fall 2025.  
                <div style="margin-bottom: 0.5cm;"></div>
                My job market paper, Market Dispatch and Emissions in U.S. Electricity Markets, studies how the adoption of market dispatch across all U.S. electricity markets reshapes generation patterns and emissions by improving operational efficiency and reallocating generation across regions.  
                <div style="margin-bottom: 0.5cm;"></div>
                Building on this work, my next project analyzes weather–energy events, focusing on how emissions and market outcomes depend jointly on weather and load conditions under both symmetric and asymmetric shocks, with particular attention to SPP–MISO  in the U.S. electricity sector.
                <div style="margin-bottom: 0.5cm;"></div>

    imageUrl: "/picture1.jpg"
    imageWidth: 260
    imageHeight: 347
    imageTitle: Sara Asgari
    buttons:
      - name: Teaching
        url: /courses/
        weight: 1
      - name: Research
        url: /papers/
        weight: 2
      - name: CV
        url: /cv.pdf
        weight: 3

  socialIcons:
    - name: CV
      url: /cv.pdf
    - name: Email
      url: mailto:sara.asgari@ou.edu
    - name: Location
      url: /location/
    - name: GitHub
      url: https://github.com/saraasgarigouraj
    - name: Linkedin
      url: https://www.linkedin.com/in/sara-a-9a6a1b182/
    - name: Twitter
      url: https://x.com/SaraAsgariEcon

  assets:
    disableHLJS: true
    disableScrollBarStyle: true

  cover:
    hiddenInList: true
    hiddenInSingle: true

  label:
    text: "Sara Asgari"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: true
    startLevel: 2
