baseURL: "https://saraasgarigouraj.github.io/" 
title: Ahmed El Fatmaoui
paginate: 14
theme: PaperMod

enableInlineShortcodes: true 
enableRobotsTXT: true  

social:
    twitter: aelfatmaoui

taxonomies:
    tag: tags

menu:
    main:
          - name: Teaching
            url: /courses/
            weight: 1
          - name: Research
            url: /papers/
            weight: 2
          - name: CV
            url: /cv.pdf
            weight: 3
        #   # weight: 1
        # - name: Design
        #   url: /design/
        #   weight: 3
        # - name: Tags
        #   url: /tags/
        #   weight: 5     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: |
        Welcome! 
        
        I am a Ph.D. Economics candidate at the University of Oklahoma - Norman. This fall, I will join the University of Wisconsin-La Crosse Department of Economics as an Assistant Professor of Economics.

        I am an applied microeconomist specializing in labor economics, economics of education, and health economics. My research examines how institutional policies and resources affect student outcomes in higher education, focusing on college costs, sports, and amenities. Additionally, I study public health policies, particularly investigating vaccination programs' impacts on maternal and infant health outcomes, and the relationship between substance legalization and healthcare decisions. My work has been recognized through multiple awards including the Southern Economic Association Graduate Student Award and the Dodge Family College of Arts and Sciences Dissertation Fellowship.
    author: Ahmed El Fatmaoui
    googleAnalyticsID: "G-WHEYZ77X40"
    DateFormat: "January 2024"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true 
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true  
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true 
    ShowWordCount: false
    UseHugoToc: true 
    comments: false
    math: true
    profileMode:
          enabled: true 
          title: "<span style='font-size: 26px;'>Ahmed El Fatmaoui</span>"
          subtitle: |
                <div style="margin-bottom: 0.2cm;"></div>
                Welcome! 
                <div style="margin-bottom: 0.5cm;"></div>
                I am a Ph.D. Economics candidate at the University of Oklahoma - Norman. This fall, I will join the University of Wisconsin-La Crosse Department of Economics as an Assistant Professor of Economics.
                <div style="margin-bottom: 0.5cm;"></div>
                I am an applied microeconomist specializing in labor economics, economics of education, and health economics. My research examines how institutional policies and resources affect student outcomes in higher education, focusing on college costs, sports, and amenities. Additionally, I study public health policies, particularly investigating vaccination programs' impacts on maternal and infant health outcomes. 
                <div style="margin-bottom: 0.5cm;"></div>
          imageUrl: "/picture.jpeg"
          #imageWidth: 280
          #imageHeight: 300
          imageWidth: 245
          imageHeight: 250
          imageTitle: Ahmed El Fatmaoui
          #imageTitle: "<span style='font-size: 12.5px;'>Ahmed El Fatmaoui</span>"
          buttons:
              - name: Teaching
                url: /courses/
                weight: 1
              - name: Research
                url: /papers/
                weight: 2
              - name: CV
                url: /cv.pdf
                weight: 3
              # - name: Design
              #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:aelfatmaoui@ou.edu
        - name: Location
          url: /location/
        # - name: Office Hours
        #   url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=EdHxr3EAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ahmedelfatmaoui?tab=repositories
        - name: Linkedin
          url: https://www.linkedin.com/in/ahmed-el-fatmaoui-75114b330/
        - name: Twitter
          url: https://x.com/ahmedelfatmaoui

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true # Set to true to hide cover images in paper
        hiddenInSingle: true
    label:
      text: "Ahmed El Fatmaoui"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: true
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265

